name: TWRPTreeGeneratorAction

on:
  workflow_dispatch:
    inputs:
      rom_url:
        description: 'ROM 下载直链'
        required: true
        default: 'https://mirrorbits.lineageos.org/full/tissot/20230425/lineage-19.1-20230425-nightly-tissot-signed.zip'

jobs:
  TWRPTreeGeneratorAction:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install python3-pip p7zip-full
          sudo apt install aria2 liblzma-dev brotli lz4
          pip3 install backports.lzma pycrypto
          pip install protobuf==3.20
          BUILD_TIME=$(TZ=Asia/Shanghai date +"%m%d%H%M")
          echo "BUILD_TIME=$BUILD_TIME" >> $GITHUB_ENV

      - name: Clone and Setup DumprX
        run: |
          cd /home
          git clone https://github.com/DumprX/DumprX
          cd DumprX
          sudo chmod 777 *.sh
          bash setup.sh

      - name: Generate Device Tree
        run: |
          cd /home/DumprX
          aria2c -s 10 -x 10 -d . -o firmware.zip "${{ github.event.inputs.rom_url }}"
          ./extractor.sh firmware.zip
          cd ${{ github.workspace }}
          touch info.md
          echo "提交日期：$(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S')" >> info.md
          echo "ROM 下载直链：${{ github.event.inputs.rom_url }}" >> info.md
          if [ -f /home/DumprX/out/init_boot.img ]; then mv /home/DumprX/out/init_boot.img /home/DumprX/out/boot.img; fi
          pip3 install twrpdtgen
          python3 -m twrpdtgen /home/DumprX/out/boot.img
          cd ~
          7z a ~/GeneratedTWRPDeviceTree.zip /home/runner/work/TWRPTreeGeneratorAction/TWRPTreeGeneratorAction/output

      - name: Upload Device Tree
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "~/GeneratedTWRPDeviceTree.zip"
          bodyfile: "${{ github.workspace }}/info.md"
          tag: "OUTPUT_${{ env.BUILD_TIME }}_${{ github.run_id }}"
          token: ${{ secrets.GITHUB_TOKEN }}
