name: TWRPTreeGeneratorAction

on:
  workflow_dispatch:
    inputs:
      rom_url:
        description: 'ROM direct download link'
        required: true
        default: 'https://assorted.downloads.oppo.com/firmware/CPH1801/CPH1801EX_11_OTA_0260_all_PDLTtXmGT1DU.ozip'

jobs:
  TWRPTreeGeneratorAction:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install python3-pip p7zip-full aria2 liblzma-dev brotli lz4
          pip3 install backports.lzma pycrypto protobuf==3.20
          BUILD_TIME=$(TZ=Asia/Shanghai date +"%m%d%H%M")
          echo "BUILD_TIME=$BUILD_TIME" >> $GITHUB_ENV

      - name: Generate Device Tree
        run: |
          cd ~
          git clone --recurse-submodules https://github.com/DumprX/DumprX.git Firmware_extractor
          cd Firmware_extractor
          aria2c -s 10 -x 10 -d . -o firmware.zip "${{ github.event.inputs.rom_url }}"
          ./setup.sh firmware.zip
          cd ${{ github.workspace }}
          touch info.md
          echo "Submission date: $(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S')" >> info.md
          echo "ROM direct download link: ${{ github.event.inputs.rom_url }}" >> info.md
          if [ -f ~/Firmware_extractor/out/init_boot.img ]; then mv ~/Firmware_extractor/out/init_boot.img ~/Firmware_extractor/out/boot.img; fi
          pip3 install twrpdtgen
          python3 -m twrpdtgen ~/Firmware_extractor/out/boot.img
          7z a ~/GeneratedTWRPDeviceTree.zip ${{ github.workspace }}/output

      - name: Upload Device Tree
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "~/GeneratedTWRPDeviceTree.zip"
          bodyfile: "${{ github.workspace }}/info.md"
          tag: "OUTPUT_${{ env.BUILD_TIME }}_${{ github.run_id }}"
          token: ${{ secrets.GITHUB_TOKEN }}
